var CmtItemsPriceSrcArrF = new Array(
"F",
"W",
"F",
"F",
"F",
"F",
"F",
"F",
"F",
"F",
"F",
"F",
"F",
"F",
"F",
"W",
"F",
"F");

var CmtItemsPriceArrF = new Array(
"62",
"0",
"52",
"33",
"120",
"90",
"62",
"44",
"47",
"59",
"102",
"62",
"0",
"0",
"0",
"0",
"0",
"0");

var CmtItemsIsHourArrF = new Array(
"Y",
"Y",
"Y",
"N",
"Y",
"Y",
"Y",
"N",
"Y",
"Y",
"Y",
"Y",
"N",
"N",
"N",
"Y",
"N",
"N");

var CmtItemsNameArrF = new Array(
"Admin Work",
"Bench Repair",
"Cabling Work",
"Computer Setup",
"Emergency <24",
"Emergency <48",
"Network Work",
"Project Management",
"Technician Level 1 Work",
"Technician Level 2 Work",
"Training and Professional Development",
"Web Design Work",
"Contract Fee",
"Managed Workstation",
"Managed Server",
"Managed Services",
"Consultation",
"Network Research-DHCP Scope Expansion");

var CmtItemsCodesArrF = new Array(
"Admin",
"Bench Repair",
"Cabling",
"Computer Setup",
"Emergency <24",
"Emergency <48",
"Network Work",
"Project Management",
"Tech1",
"Tech2",
"Training",
"WebDesign",
"yCMT-ContractFee.",
"yCMT-MngPC.",
"yCMT-MngSrv.",
"yManaged Services",
"zConsultation",
"zNetwork Research");

var CmtItemsRecIdArrF = new Array(
{"RecId":"ITMMLPS0M8OR6KKK8A4S"},
{"RecId":"ITMVQ7MARCLKMTZSS59R"},
{"RecId":"ITMIVM8MZFOLLDETWOLK"},
{"RecId":"ITMX6BR0K40DBTL2LGOJ"},
{"RecId":"ITMWQYN7Y267YCH845P4"},
{"RecId":"ITMDHRI7O4Y2ZY4MY4LL"},
{"RecId":"ITMM5517G1FAUKWK9F6Q"},
{"RecId":"ITMIJEFT8P43GYQHR4T8"},
{"RecId":"ITMGGUT7P5KC6FBRA2B0"},
{"RecId":"ITMO16PAZ8GGRNKWYZN8"},
{"RecId":"ITMMBOPR4913EEMLIP7Q"},
{"RecId":"ITM3HA1A5DR9QYWO67SU"},
{"RecId":"ITMCCRM123VGCZ0PV3MY"},
{"RecId":"ITMCCRM123ZDICOADTGP"},
{"RecId":"ITMCCRM1230CDJDOQJWC"},
{"RecId":"ITMTAL5TGM28381RNS2J"},
{"RecId":"ITMIYUN84E0RU5RPXV9Z"},
{"RecId":"ITM50K7SNL0RANKAOF5S"});

var CmtItemsDescByNameArrF = new Array(
"Y",
"Y",
"Y",
"Y",
"Y",
"Y",
"Y",
"N",
"Y",
"Y",
"Y",
"Y",
"Y",
"Y",
"Y",
"Y",
"Y",
"N");

var CmtItemsDescArrF = new Array(
"",
"",
"",
"",
"",
"",
"",
"Includes, but not limited to project time involving: consultations, meetings, scheduling, ordering parts, adjusting schedules, and tracking the project.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"1) Check current scope and see how big it is, what is excluded, what is reserved.\n2) IP scan of the network and see what has a web facing, ssh facing device and see if I have access to it. Third party systems need to be discussed to ensure third party knows and willing to make change on schedule day. Match what is web facing and ssh facing to anything that has a reservation or has an IP address in the excluded range.\n3) Ensure access to firewall, wireless controller(if APs are static), printers, and servers.(Phone system would require advance notice to school and ensure you get vendor info)");

